seed: 0
model_type: albert4rec
dataset:
  calc_date: "2025-08-21"
  hdfs_working_prefix: "hdfs:///user/antonchernov/bert4recv1/tc5/"
  user_column: loyalty_cardholder_rk
  product_column: product_id
  state_size: 50
  use_sanity_subset: false
bert4rec_loo:
  enable: true
  val_samples_num: 100_000
  test_samples_num: 100_000
limit_chunks_pct: 0.1
data: data
epoch: 80
enable_sa2c: false

purchase_only: false

batch_size_train: 400
batch_size_val: 128
num_workers_train: 0
num_workers_val: 0
device_id: cuda:0

hidden_factor: 64
num_heads: 1
num_blocks: 1
dropout_rate: 0.1

albert4rec:
  masking_proba: 0.2
  n_negatives: 256
  intermediate_size: null

r_click: 0.2
r_buy: 1.0

lr: 0.0005

max_steps: 0
debug: false

early_stopping_ep: 10
early_stopping_metric: ndcg@10

